### ISSUE TITLE
Form's helper validation method being called twice when form is triggered with pre-existing slot with invalid value

### ISSUE THREAD

**Issue by naagbharath** [RasaHQ/rasa-sdk#100] opened 2019-08-22 14:57 UTC
**Rasa version**: 1.1.3

**Rasa SDK version**: 1.1.0

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): Windows Server 2016

**Issue**:
I am using forms to obtain some info, fill two slots and execute a custom action. When the user sends a message which contains an entity belonging to a certain intent, it fills the corresponding slot and triggers the form. I have a helper validation method, to validate the slots, where i'm returning {<slot_name>, value} if validation succeeds else print an error message and return {<slot_name>, None}.
The issue here is that in case of an invalid value the helper validation method is being called subsequently twice and hence the error message is being printed twice. 
I could observe this behavior only in the case where the form is triggered when the first of the two slots is prefilled with an invalid value. It works fine when triggered with none of the slots filled or when the second slot filled with an invalid value.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Contents of stories.md**
```
## Form story
* intent_slot1
  - action_form
  - form{"name": "action_form"}
  - form{"name": null}
  - utter_done
```

**Contents of actions.py** (if  relevant):
```python
class ActionForm(FormAction):"

	def name(self) -> Text:
		return "action_form"

	@staticmethod
	def required_slots(tracker: Tracker) -> List[Text]:
		return ["slot1", "slot2"]

	def request_next_slot(self, dispatcher, tracker, domain):
		
		for slot in self.required_slots(tracker):
			if self._should_request_slot(tracker, slot):
				if slot == 'slot1':
					dispatcher.utter_button_message("Select an option for slot1",slot1_buttons)
					
				if slot == 'slot2':
					dispatcher.utter_button_message("Select an option for slot2",slot2_buttons)
					
				return [SlotSet("requested_slot", slot)]
		return None

	def validate_slot1(
		self,
		value: Text,
		dispatcher: CollectingDispatcher,
		tracker: Tracker,
		domain: Dict[Text, Any],
	) -> Optional[Text]:

		if type(value)==type([]):
			value=value[-1]
		value=value.lower()

		if value in valid_values_for_slot1:
			return {"application": value}
		else:
			dispatcher.utter_message(f"I'm sorry, entered value for {slot1} is invalid! Please try again...")
			return {"application": None}

	def validate_slot2(
		self,
		value: Text,
		dispatcher: CollectingDispatcher,
		tracker: Tracker,
		domain: Dict[Text, Any],
	) -> Optional[Text]:

		if type(value)==type([]):
			value=value[-1]
		value=value.lower()

		if value in valid_values_for_slot2:
			return {"application": value}
		else:
			dispatcher.utter_message(f"I'm sorry,  entered value for {slot2} is invalid! Please try again...")
			return {"application": None}

	def submit(
		self,
		dispatcher: CollectingDispatcher,
		tracker: Tracker,
		domain: Dict[Text, Any],
	) -> List[Dict]:

		if tracker.get_slot("slot3"):
			return [{"event": "followup", "name": "action_do_something"}]
		
		return [{"event": "reset_slots"}]
```

**Comment by naagbharath** [comment] 2019-08-23 07:40
Correction: The issue occurs even when the second slot is prefilled with an invalid value. On further testing after adding a few debug statements, I could observe that the helper validation methods are called twice regardless of the slot prefilled with valid or invalid values.
Observations: 
1. When the form is triggered with any of the required slots prefilled with valid/invalid values the helper validation method for that slot is called twice.
2.When the form is triggered with both slots prefilled with invalid valid/values, the helper validations methods for both slots are called twice.

**Comment by akelad** [comment] 2019-08-23 08:30
Thanks for raising this issue, @Ghostvv will get back to you about it soon

**Comment by Ghostvv** [comment] 2019-08-23 10:57
Hi, just checked it with format example, couldn't reproduce

**Comment by naagbharath** [comment] 2019-08-23 12:31
Thanks for the response. Do you suspect anything wrong in my configuration or code? I added debug statements in all the methods and could see that:
required_slots is called
redirected to validate_slot1
validation fails
required slots called again
redirected to validate_slot1 again
validation fails again

If you can notice from the logs below, Action 'action_form' ended with events, has three 'BotUttered' events; two for the failed validation and one to fill the slot which failed validation.

**Logs**:
```
2019-08-23 17:22:39 DEBUG    websockets.protocol  - undefined < Frame(fin=True, opcode=1, data=b'42["user_uttered",{"message":"slot1_value","customData":{},"session_id":"09a6a30af15d483292f02e4a69a684ab"}]', rsv1=False, rsv2=False, rsv3=False)
2019-08-23 17:22:39 INFO     engineio.server  - 1eb4ec892d3d42b5848896d7111b4982: Received packet MESSAGE data 2["user_uttered",{"message":"slot1_value","customData":{},"session_id":"09a6a30af15d483292f02e4a69a684ab"}]
2019-08-23 17:22:39 INFO     socketio.server  - received event "user_uttered" from 1eb4ec892d3d42b5848896d7111b4982 [/]
2019-08-23 17:22:39 DEBUG    rasa.core.agent  - Created a new lock for conversation '1eb4ec892d3d42b5848896d7111b4982'
2019-08-23 17:22:39 DEBUG    rasa.core.tracker_store  - Creating a new tracker for id '1eb4ec892d3d42b5848896d7111b4982'.
2019-08-23 17:22:39 DEBUG    rasa.core.processor  - Received user message 'slot1_value' with intent '{'name': 'intent_slot1', 'confidence': 0.8952854871749878}' and entities '[{'start': 0, 'end': 4, 'value': 'slot1_value', 'entity': 'slot1', 'confidence': 0.9967250983022973, 'extractor': 'CRFEntityExtractor'}]'
2019-08-23 17:22:39 DEBUG    rasa.core.processor  - Current slot values:
        slot1: slot1_value
        slot2: None
        requested_slot: None
2019-08-23 17:22:39 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 3 events
2019-08-23 17:22:39 DEBUG    rasa.core.policies.form_policy  - There is no active form
2019-08-23 17:22:39 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, {}, {'prev_action_listen': 1.0, 'intent_intent_slot1': 1.0, 'entity_slot1': 1.0}]
2019-08-23 17:22:39 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2019-08-23 17:22:39 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-23 17:22:39 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_2_KerasPolicy
2019-08-23 17:22:39 DEBUG    rasa.core.processor  - Predicted next action 'action_form' with confidence 0.97.
2019-08-23 17:22:39 DEBUG    rasa.core.actions.action  - Calling action endpoint to run action 'action_form'.
2019-08-23 17:22:40 DEBUG    rasa.core.processor  - Action 'action_form' ended with events '['BotUttered(text: I\'m sorry, entered value for slot1 is invalid! Please try again..., data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})', 'BotUttered(text: I\'m sorry, entered value for slot1 is invalid! Please try again..., data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})', 'BotUttered(text: Select an option for slot1, data: {"elements": null, "quick_replies": null, "buttons": [], "attachment": null, "image": null, "custom": null}, metadata: {})', 'Form(action_form)', 'SlotSet(key: slot1, value: None)', 'SlotSet(key: slot1, value: None)', 'SlotSet(key: requested_slot, value: slot1)']'
2019-08-23 17:22:40 DEBUG    rasa.core.processor  - Current slot values:
        slot1: None
        slot2: None
        requested_slot: slot1
2019-08-23 17:22:40 INFO     socketio.server  - emitting event "bot_uttered" to 1eb4ec892d3d42b5848896d7111b4982 [/]
2019-08-23 17:22:41 INFO     engineio.server  - 1eb4ec892d3d42b5848896d7111b4982: Sending packet MESSAGE data 2["bot_uttered",{"text":"I'm sorry, entered value for slot1 is invalid! Please try again..."}]
2019-08-23 17:22:41 INFO     socketio.server  - emitting event "bot_uttered" to 1eb4ec892d3d42b5848896d7111b4982 [/]
2019-08-23 17:22:41 DEBUG    websockets.protocol  - undefined > Frame(fin=True, opcode=1, data=b'42["bot_uttered",{"text":"I\'m sorry, entered value for slot1 is invalid! Please try again..."}]', rsv1=False, rsv2=False, rsv3=False)
2019-08-23 17:22:41 INFO     engineio.server  - 1eb4ec892d3d42b5848896d7111b4982: Sending packet MESSAGE data 2["bot_uttered",{"text":"I'm sorry, entered value for slot1 is invalid! Please try again..."}]
2019-08-23 17:22:41 INFO     socketio.server  - emitting event "bot_uttered" to 1eb4ec892d3d42b5848896d7111b4982 [/]
2019-08-23 17:22:41 DEBUG    websockets.protocol  - undefined > Frame(fin=True, opcode=1, data=b'42["bot_uttered",{"text":"I\'m sorry, entered value for slot1 is invalid! Please try again..."}]', rsv1=False, rsv2=False, rsv3=False)
2019-08-23 17:22:41 INFO     engineio.server  - 1eb4ec892d3d42b5848896d7111b4982: Sending packet MESSAGE data 2["bot_uttered",{"text":"Select an option for slot1"}]
2019-08-23 17:22:41 DEBUG    rasa.core.policies.form_policy  - There is an active form 'action_form'
2019-08-23 17:22:41 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, {}, {'prev_action_listen': 1.0, 'intent_intent_slot1': 1.0, 'entity_slot1': 1.0}]
2019-08-23 17:22:41 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2019-08-23 17:22:41 DEBUG    rasa.core.policies.mapping_policy  - There is no mapped action for the predicted intent, 'intent_slot1'.
2019-08-23 17:22:41 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-23 17:22:41 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_0_FormPolicy
2019-08-23 17:22:41 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with confidence 1.00.
2019-08-23 17:22:41 DEBUG    rasa.core.processor  - Action 'action_listen' ended with events '[]'
```

**Contents of actions.py** (with debug statements):
```python
class ActionForm(FormAction):"

	def name(self) -> Text:
		return "action_form"

	@staticmethod
	def required_slots(tracker: Tracker) -> List[Text]:
		#Debug Statement
		print("in required_slots")
		
		return ["slot1", "slot2"]

	def request_next_slot(self, dispatcher, tracker, domain):
		#Debug Statement
		print("in request_next_slot")
		
		for slot in self.required_slots(tracker):
			if self._should_request_slot(tracker, slot):
				
				#Debug Statement
				print("in _should_request_slot")
				
				if slot == 'slot1':
					dispatcher.utter_button_message("Select an option for slot1",slot1_buttons)
					
				if slot == 'slot2':
					dispatcher.utter_button_message("Select an option for slot2",slot2_buttons)
					
				return [SlotSet("requested_slot", slot)]
		return None

	def validate_slot1(
		self,
		value: Text,
		dispatcher: CollectingDispatcher,
		tracker: Tracker,
		domain: Dict[Text, Any],
	) -> Optional[Text]:

		#Debug Statement
		print("in validate_slot1")
		
		if type(value)==type([]):
			value=value[-1]
		value=value.lower()

		if value in valid_values_for_slot1:
			return {"application": value}
		else:
			dispatcher.utter_message(f"I'm sorry, entered value for {slot1} is invalid! Please try again...")
			
			#Debug Statement
			print("slot1 validation failed")
			
			return {"application": None}

	def validate_slot2(
		self,
		value: Text,
		dispatcher: CollectingDispatcher,
		tracker: Tracker,
		domain: Dict[Text, Any],
	) -> Optional[Text]:

		#Debug Statement
		print("in validate_slot2")
		
		if type(value)==type([]):
			value=value[-1]
		value=value.lower()

		if value in valid_values_for_slot2:
			return {"application": value}
		else:
			dispatcher.utter_message(f"I'm sorry,  entered value for {slot2} is invalid! Please try again...")
			
			#Debug Statement
			print("slot2 validation failed")
			
			return {"application": None}

	def submit(
		self,
		dispatcher: CollectingDispatcher,
		tracker: Tracker,
		domain: Dict[Text, Any],
	) -> List[Dict]:

		if tracker.get_slot("slot3"):
			return [{"event": "followup", "name": "action_do_something"}]
		
		return [{"event": "reset_slots"}]
```

**Actions Server log (Debug statements)**:
```
in required_slots
in validate_slot1
slot1 validation failed
in required_slots
in validate_slot1
slot1 validation failed
in request_next_slot
in required_slots
in _should_request_slot
```

**Comment by Ghostvv** [comment] 2019-08-23 12:53
It happens if you have refilled slots, but also provide an entity again during input. Then first time, prefilled slots got validated, then your input gets validated. If your input fills the same slots, it looks like validation was called two times

**Comment by naagbharath** [comment] 2019-08-23 13:40
But in my case, the prefilled slot is getting validated twice before it even goes to the stage where it asks user for input. But later when I give the input, it gets validated only once. 
I confirmed this by printing out the value in the helper validation method for slot1. The prefilled slot value is printed twice and only after that it asks me to enter the right value. This time when I enter a value it is only printed once.

**Comment by Ghostvv** [comment] 2019-08-23 14:29
what input do you use to activate the form?

**Comment by naagbharath** [comment] 2019-08-23 15:39
The input is a text (which is the name of a site the user is looking for) which is mapped to an entity. This entity is part of an intent which triggers the form.

**Comment by Ghostvv** [comment] 2019-08-23 15:53
is the corresponding is set before as well? then double validation is first the slot then the entity

**Comment by naagbharath** [comment] 2019-08-23 17:09
The slot gets set when the entity is extracted. According to the Rasa conventions for forms, the slots need to have the same names as the entities right? Do you suggest I name the slot for this certain entity differently in this case?

**Comment by Ghostvv** [comment] 2019-08-25 15:08
It depends on the design of your bot. Since it is more of a discussion now, I'll close the issue. Please ask question about best practices on our forum: https://forum.rasa.com

**Closed by Ghostvv** 2019-08-25 15:08 UTC

**Comment by naagbharath** [comment] 2019-09-03 16:24
On further analyzing forms.py, I could see that the prefilled slots are validated when the form is initially activated and are validated again after the slots are mapped to the entities. I have not defined slot mappings as the slots I am using are the same names as the entities. In this case, I believe there needs to be a condition to check if the slot has already been validated and if so, skip validation. But I see no such condition and validation happens regardless, which results in a double validation. 
I also observed that when i name the slots differently from the entities, define slot mappings and activate the form with prefilled values for the entities, the entities are not being mapped to the slots, which results in the form asking for the requested slots to be filled even though the form is activated with prefilled entity values.

**Comment by Ghostvv** [comment] 2019-09-09 09:39
First, it validates the slots that were filled before, second, it validates the entities in the user input before filling the slots. If you activate the form with entities and same slots are already filled, the form will call validation twice but in reality it validates different things
